### ISSUE TITLE
Phyto plot naming order.

### ISSUE THREAD

**Issue by SamRobinson113** [Bartesto/rivRmon#5]
the sites for both the Canning and Swan are in alphabetical order and not actual sampling order. Can this be changed?
[2019-10-28_SG-E-SWANEST_summary_plots MASTER.pdf](https://github.com/Bartesto/rivRmon/files/3796914/2019-10-28_SG-E-SWANEST_summary_plots.MASTER.pdf)

Older rivRmon output has the right site order but font size too big! (see below):
[2019-10-28_SG-E-SWANEST_summary_plots.pdf](https://github.com/Bartesto/rivRmon/files/3796918/2019-10-28_SG-E-SWANEST_summary_plots.pdf)

**Comment by Bartesto** [comment]
@SamRobinson113 please send through the data. It would be good to have all data after the 01/10/2019. Cheers

**Comment by SamRobinson113** [comment]
I hope this is what you need?

[20191021_SWANEST_COC67350-64586_raw.xlsx](https://github.com/Bartesto/rivRmon/files/3797081/20191021_SWANEST_COC67350-64586_raw.xlsx)
[20191028_SG-E-SWANEST_COC64590_raw.xlsx](https://github.com/Bartesto/rivRmon/files/3797082/20191028_SG-E-SWANEST_COC64590_raw.xlsx)
[20191007_SWANEST_COC67335-36_raw.xlsx]
(https://github.com/Bartesto/rivRmon/files/3797083/20191007_SWANEST_COC67335-36_raw.xlsx)
[20191014_SWANEST_COC67343_67345_raw.xlsx](https://github.com/Bartesto/rivRmon/files/3797084/20191014_SWANEST_COC67343_67345_raw.xlsx)

the code I have been using:
library(rivRmon)
phyto_groupR(pathin = "T:/671-River System Management/Shared Data/Prgms/REScience/2. Projects/1. Monitoring/1. Data/1. SWANEST/6. PEU/2. Raw Data", pathout = "T:/671-River System Management/Shared Data/Prgms/REScience/2. Projects/1. Monitoring/1. Data/1. SWANEST/6. PEU/3. Edited Data")
phyto_plotR(summary = "T:/671-River System Management/Shared Data/Prgms/REScience/2. Projects/1. Monitoring/1. Data/1. SWANEST/6. PEU/3. Edited Data", date = "20191028")

**Comment by Bartesto** [comment]
Have tested current package on the supplied data and not been able to recreate the issue.

Suggest re-install of the package. If issues still persists will trial package on offending computer to rule out other possibilities.

**Comment by Bartesto** [comment]
Have now tested on @SamRobinson113 machine. Initially was still creating the issue.

Stepped through a "manual" version of the phyto_plotR function, produced graphical output to RStudio (which was correct) and saved output with ggsave. This produced correct output.

Retested with installed with rivRmon phyto_plotR function and now output is as intended. Not sure what fixed the issue.

**Comment by SamRobinson113** [comment]
Hi Bart,

Its doing it again…?

[cid:image001.png@01D59624.62D1BFC0]


Sam Robinson
Environmental Officer
Rivers and Estuaries Science
Department of Biodiversity,
Conservation and Attractions
P: 08 9278 1983   E: sam.robinson@dbca.wa.gov.au<mailto:sam.robinson@dbca.wa.gov.au>

**Comment by SamRobinson113** [comment]
Hi Bart,

We are currently having trouble getting our phyto plots to work and as such I have tried to re-install rivRmon. I got the error saying I had a problem with rlang, which I then deleted, and now I can't find it to re-install it or run "devtools::install_github("Bartesto/rivRmon")".

The downloaded binary packages are in
        C:\Users\samrobinson\AppData\Local\Temp\RtmpENUKBp\downloaded_packages
> devtools::install_github("Bartesto/rivRmon")
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  there is no package called 'rlang'
> library(rivRmon)
Error in library(rivRmon) : there is no package called 'rivRmon'
> devtools::install_github("Bartesto/rivRmon")
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  there is no package called 'rlang'

I'm making a basic error here, but I can't see the wood for the trees!

Sam

Sam Robinson
Environmental Officer
Rivers and Estuaries Science
Department of Biodiversity,
Conservation and Attractions
17 Dick Perry Avenue
Kensington WA 6151
P: 08 9278 1983
E: sam.robinson@dbca.wa.gov.au<mailto:sam.robinson@dbca.wa.gov.au>

[cid:image001.png@01D5DCEE.2A140560]

________________________________
This message is confidential and is intended for the recipient named above. If you are not the intended recipient, you must not disclose, use or copy the message or any part of it. If you received this message in error, please notify the sender immediately by replying to this message, then delete it from your system.

**Comment by SamRobinson113** [comment]
Are you there now? I can come and help


From: Sam Robinson <sam.robinson@dbca.wa.gov.au>
Sent: Thursday, 6 February 2020 1:07 PM
To: Bartesto/rivRmon <reply@reply.github.com>; Bart Huntley <bart.huntley@dbca.wa.gov.au>
Subject: can't find a package

Hi Bart,

We are currently having trouble getting our phyto plots to work and as such I have tried to re-install rivRmon. I got the error saying I had a problem with rlang, which I then deleted, and now I can't find it to re-install it or run "devtools::install_github("Bartesto/rivRmon")".

The downloaded binary packages are in
        C:\Users\samrobinson\AppData\Local\Temp\RtmpENUKBp\downloaded_packages
> devtools::install_github("Bartesto/rivRmon")
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  there is no package called 'rlang'
> library(rivRmon)
Error in library(rivRmon) : there is no package called 'rivRmon'
> devtools::install_github("Bartesto/rivRmon")
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  there is no package called 'rlang'

I'm making a basic error here, but I can't see the wood for the trees!

Sam

Sam Robinson
Environmental Officer
Rivers and Estuaries Science
Department of Biodiversity,
Conservation and Attractions
17 Dick Perry Avenue
Kensington WA 6151
P: 08 9278 1983
E: sam.robinson@dbca.wa.gov.au<mailto:sam.robinson@dbca.wa.gov.au>

[cid:image001.png@01D5DCF1.1B1E5760]

________________________________
This message is confidential and is intended for the recipient named above. If you are not the intended recipient, you must not disclose, use or copy the message or any part of it. If you received this message in error, please notify the sender immediately by replying to this message, then delete it from your system.
