### ISSUE TITLE
Use here::here()

### ISSUE THREAD

**Issue by florianm** [Bartesto/rivRmon#7]
Replace absolute, os-dependent paths with here::here() relative paths [lest bad things happen](https://twitter.com/hadleywickham/status/940021008764846080)

**Comment by Bartesto** [comment]
Got another month of developer time on this so will add to list of _things to do_

Thanks Flo

**Comment by Bartesto** [comment]
Users still need flexability to point functions to where they need to. I am enforcing a package structure so no need for this at this stage
